# Generated by Django 4.2.20 on 2025-03-31 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("steps", "0002_rename_user_steprecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steprecord",
            name="date",
            field=models.DateField(default=datetime.date(2025, 3, 31)),
        ),
    ]
