# Generated by Django 4.2.20 on 2025-04-04 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("steps", "0005_workouts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workouts",
            old_name="reps",
            new_name="calories_burned",
        ),
        migrations.RenameField(
            model_name="workouts",
            old_name="sets",
            new_name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="workouts",
            name="Workout_name",
        ),
        migrations.AddField(
            model_name="workouts",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workouts",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("weightlifting", "Weightlifting"),
                    ("cycling", "Cycling"),
                    ("yoga", "Yoga"),
                    ("swimming", "Swimming"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
